CREATE TABLE DEPARTMENTS(
dept_no VARCHAR PRIMARY KEY,
dept_name VARCHAR NOT NULL
);

--Next table creation
CREATE TABLE TITLES(
title_id VARCHAR PRIMARY KEY,
title VARCHAR NOT NULL
);

CREATE TABLE EMPLOYEE(
emp_no INT PRIMARY KEY,
emp_title_id VARCHAR NOT NULL,
birth_date DATE NOT NULL,
first_name VARCHAR(20) NOT NULL,
last_name VARCHAR NOT NULL,
sex VARCHAR NOT NULL,
hire_date DATE NOT NULL,
FOREIGN KEY(emp_title_id) REFERENCES TITLES(title_id)
);

--Next table creation

CREATE TABLE DEPT_EMP(
emp_no INT NOT NULL,
dept_no VARCHAR NOT NULL,
FOREIGN KEY(emp_no) REFERENCES EMPLOYEE(emp_no),
FOREIGN KEY(dept_no) REFERENCES DEPARTMENTS(dept_no)
);

-- Next table creation

CREATE TABLE MANAGERS(
dept_no VARCHAR NOT NULL,
emp_no INT NOT NULL,
FOREIGN KEY(dept_no) REFERENCES DEPARTMENTS(dept_no),
FOREIGN KEY(emp_no) REFERENCES EMPLOYEE(emp_no)
);

--Next Table creation

CREATE TABLE SALARIES(
emp_no INT NOT NULL,
salary INT NOT NULL,
FOREIGN KEY(emp_no) REFERENCES EMPLOYEE(emp_no)
);